In [1]:
import datetime
from StringIO import StringIO

import pandas as pd
from talib import abstract

import time
import urllib
import urllib2

from BeautifulSoup import BeautifulSoup


def get(url, data_list=None, timeout=10, max_try=3):

    if data_list:
        url = "{}?{}".format(url, urllib.urlencode(data_list))
    query = urllib2.Request(url)
    current_try = 0
    while current_try < max_try:
        try:
            response = urllib2.urlopen(query, timeout=timeout)
            html = response.read()
            response.close()
            return html
        except Exception, e:
            print e
            current_try += 1
            time.sleep(timeout)
    raise Exception("Cannot open page {}".format(url))


def get_yahoo_finance_data(symbol, start_date=None, end_date=None, remove_zero_volume=True):
    """
    Using yahoo finance API Get stock price with high low open close data

    :param symbol: stock symbol used in yahoo finance
    :param start_date: start date of the given stock data 2012-03-15
    :param end_date: end data
    :param remove_zero_volume: if True, will remove all data with zero volume
    :return: a list of stock price as [date, open, high, low, close]
    """
    data_list = [('s', symbol)]
    if start_date:
        data = start_date.split('-')
        data_list.append(('a', int(data[1]) - 1))
        data_list.append(('b', data[2]))
        data_list.append(('c', data[0]))
    if end_date:
        data = end_date.split('-')
        data_list.append(('d', int(data[1]) - 1))
        data_list.append(('e', data[2]))
        data_list.append(('f', data[0]))
    data_list.append(('g', 'd'))
    data_list.append(('ignore', '.csv'))

    url = "http://chart.finance.yahoo.com/table.csv"
    stock_info = get(url=url, data_list=data_list)
    stock_data = StringIO(stock_info)
    stock_df = pd.read_csv(stock_data)
    stock_df['Date'] = stock_df['Date'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))
    stock_df = stock_df.set_index('Date')

    if not remove_zero_volume:
        return stock_df

    return stock_df[stock_df['Volume'] > 0]

In [2]:
df = get_yahoo_finance_data('0001.HK')
df

                Open      High       Low     Close    Volume  Adj Close
Date
2016-09-30   98.5000   99.1500   98.0500   98.6000   6769200   98.60000
2016-09-29   99.4000  100.2000   99.2500   99.7000   4066000   99.70000
2016-09-28   98.3000   99.3500   98.0000   99.3500   4793900   99.35000
2016-09-27   99.0000   99.2500   98.5500   99.0000   4681700   99.00000
2016-09-26   99.9000   99.9500   99.0000   99.2000   3059500   99.20000
2016-09-23  100.4000  101.4000   99.8500  100.3000   3470300  100.30000
2016-09-22  100.6000  101.9000  100.2000  100.4000   4875900  100.40000
2016-09-21   99.0500   99.7000   98.4000   99.7000   7077500   99.70000
2016-09-20  100.4000  101.0000   99.4000   99.6000   4264100   99.60000
2016-09-19  101.0000  101.3000   99.8000  101.2000   4079100  101.20000
2016-09-15   99.7000  100.7000   99.3000   99.8500   4301600   99.85000
2016-09-14   99.7500  100.5000   99.0000   99.7000   3163400   99.70000
2016-09-13  100.9000  101.0000   99.2500   99.2500   4153000   99.25000
2016-09-12  100.9000  100.9000   99.5000   99.5000   7738600   99.50000
2016-09-09  101.8000  103.9000  101.5000  102.3000   5963300  102.30000
2016-09-08  101.5000  102.6000  101.5000  102.2000   5459200  101.46500
2016-09-07  103.0000  103.0000  102.0000  102.1000   4926700  101.36572
2016-09-06  102.7000  103.2000  102.0000  102.2000   5209500  101.46500
2016-09-05  103.3000  103.9000  102.8000  103.2000   3620100  102.45781
2016-09-02  100.0000  103.8000   99.8000  102.8000  12236700  102.06069
2016-09-01   99.7000   99.7000   98.7000   99.5500   6533800   98.83406
2016-08-31   98.7500   99.7000   98.6000   99.7000   3698700   98.98298
2016-08-30   99.3000   99.7000   98.7000   99.1500   4041600   98.43694
2016-08-29   99.3000   99.3000   97.8000   98.8500   2644900   98.13909
2016-08-26   99.5000   99.6000   98.5500   98.7500   3664600   98.03981
2016-08-25   98.3000   98.3500   97.2000   98.0000   4863900   97.29521
2016-08-24   99.0000   99.1000   97.8500   98.8000   3005600   98.08946
2016-08-23   97.8000   99.0000   97.6000   99.0000   4776500   98.28801
2016-08-22   97.2000   98.2000   97.0000   98.0500   4021200   97.34485
2016-08-19   98.2000   98.6000   96.8000   97.2500   4929200   96.55060
...              ...       ...       ...       ...       ...        ...
2000-02-16   77.9043   78.6190   76.4748   77.9043   7014600   41.56509
2000-02-15   81.8352   82.1926   74.3307   77.5469  10268200   41.37441
2000-02-14   87.1956   87.1956   81.1205   81.8352   5595700   43.66239
2000-02-11   81.8352   88.2677   81.4779   86.4809   8254200   46.14106
2000-02-10   76.4748   83.6220   76.1175   80.0484  10401000   42.70906
2000-02-09   75.0454   78.6190   74.3307   77.5469   8507900   41.37441
2000-02-08   73.2586   75.7601   71.4718   75.0454   4574600   40.03976
2000-02-03   72.9013   73.6160   70.9358   73.2586   4005700   39.08642
2000-02-02   71.1144   73.2586   71.1144   72.9013   4732200   38.89579
2000-02-01   71.2931   71.4718   69.3277   70.7571   5250300   37.75177
2000-01-31   71.4718   71.4718   69.6850   69.8637   5745800   37.27511
2000-01-28   73.6160   73.9733   71.2931   73.2586   8468800   39.08642
2000-01-27   70.3997   72.9013   70.2211   72.9013   6492400   38.89579
2000-01-26   68.2556   70.3997   68.2556   70.0424   5974600   37.37045
2000-01-25   66.4688   68.4343   66.1114   67.7195   4556300   36.13109
2000-01-24   67.1835   68.6129   65.9327   66.8261   5841400   35.65443
2000-01-21   65.7541   67.5409   64.8607   65.9327   5885900   35.17776
2000-01-20   65.7541   66.6475   65.3967   65.5754   4246000   34.98713
2000-01-19   65.0394   65.7541   64.3246   65.7541   7926100   35.08247
2000-01-18   62.7165   66.8261   62.7165   66.4688   4871500   35.46379
2000-01-17   63.6099   63.6099   62.3592   63.2525   3106900   33.74777
2000-01-14   63.6099   64.1460   61.6444   62.5378   3903500   33.36644
2000-01-13   64.6820   64.8607   63.0739   63.4312   3499800   33.84311
2000-01-12   64.3246   65.9327   63.4312   64.3246   5453800   34.31977
2000-01-11   65.3967   66.1114   63.9673   65.3967   6175800   34.89178
2000-01-10   65.3967   66.4688   63.7886   63.7886   5195400   34.03380
2000-01-07   62.8952   63.6099   61.8231   63.2525   6049700   33.74777
2000-01-06   65.7541   66.1114   60.7510   62.0018  10440400   33.08047
2000-01-05   66.8261   67.8982   64.8607   65.2180   6058500   34.79644
2000-01-04   71.4718   72.1865   70.0424   70.0424   3194400   37.37045

[4107 rows x 6 columns]

In [3]:
from talib import abstract
df = df.sort_index()
df['close'] = df['Close']
macd_df = abstract.MACD(df, 7, 14, 9)
macd_df

                macd  macdsignal  macdhist
Date
2000-01-04       NaN         NaN       NaN
2000-01-05       NaN         NaN       NaN
2000-01-06       NaN         NaN       NaN
2000-01-07       NaN         NaN       NaN
2000-01-10       NaN         NaN       NaN
2000-01-11       NaN         NaN       NaN
2000-01-12       NaN         NaN       NaN
2000-01-13       NaN         NaN       NaN
2000-01-14       NaN         NaN       NaN
2000-01-17       NaN         NaN       NaN
2000-01-18       NaN         NaN       NaN
2000-01-19       NaN         NaN       NaN
2000-01-20       NaN         NaN       NaN
2000-01-21       NaN         NaN       NaN
2000-01-24       NaN         NaN       NaN
2000-01-25       NaN         NaN       NaN
2000-01-26       NaN         NaN       NaN
2000-01-27       NaN         NaN       NaN
2000-01-28       NaN         NaN       NaN
2000-01-31       NaN         NaN       NaN
2000-02-01       NaN         NaN       NaN
2000-02-02  1.666477    1.057813  0.608663
2000-02-03  1.744349    1.195121  0.549229
2000-02-08  1.945282    1.345153  0.600129
2000-02-09  2.302887    1.536700  0.766187
2000-02-10  2.750409    1.779441  0.970967
2000-02-11  3.700076    2.163568  1.536508
2000-02-14  3.652026    2.461260  1.190766
2000-02-15  2.998757    2.568759  0.429998
2000-02-16  2.515871    2.558182 -0.042311
...              ...         ...       ...
2016-08-19  1.715830    1.641628  0.074202
2016-08-22  1.628736    1.639050 -0.010314
2016-08-23  1.628667    1.636973 -0.008306
2016-08-24  1.551000    1.619778 -0.068779
2016-08-25  1.355483    1.566919 -0.211436
2016-08-26  1.270714    1.507678 -0.236964
2016-08-29  1.184924    1.443127 -0.258203
2016-08-30  1.124663    1.379435 -0.254772
2016-08-31  1.112171    1.325982 -0.213811
2016-09-01  1.049479    1.270681 -0.221202
2016-09-02  1.352913    1.287128  0.065786
2016-09-05  1.551715    1.340045  0.211670
2016-09-06  1.512546    1.374545  0.138000
2016-09-07  1.425001    1.384636  0.040364
2016-09-08  1.332263    1.374162 -0.041899
2016-09-09  1.239242    1.347178 -0.107936
2016-09-12  0.810803    1.239903 -0.429100
2016-09-13  0.476124    1.087147 -0.611023
2016-09-14  0.295213    0.928760 -0.633548
2016-09-15  0.185279    0.780064 -0.594785
2016-09-19  0.265147    0.677081 -0.411934
2016-09-20  0.121556    0.565976 -0.444420
2016-09-21  0.035836    0.459948 -0.424111
2016-09-22  0.060591    0.380076 -0.319485
2016-09-23  0.062995    0.316660 -0.253665
2016-09-26 -0.065875    0.240153 -0.306029
2016-09-27 -0.170779    0.157967 -0.328745
2016-09-28 -0.192440    0.087885 -0.280325
2016-09-29 -0.159272    0.038454 -0.197726
2016-09-30 -0.260737   -0.021384 -0.239352

[4107 rows x 3 columns]